export const DEFAULT_DATA = {
  sectors: [
    "Auto",
    "Banks",
    "Chemicals",
    "Consumer Durables / Non Durables",
    "Defence",
    "Electronics",
    "Finance",
    "IT",
    "Manufacturing",
    "Metals/Minerals",
    "Oil Refinery",
    "Pharma",
    "Miscellaneous",
    "Electricals",
    "Construction",
    "Communications",
  ],

  paramDefinitions: {
    stage: {
      label: "Stage",
      type: "select",
      options: ["Stage 1", "Stage 2", "Stage 3", "Stage 4"],
      filterable: true,
      isCheck: true,
      idealValues: ["Stage 2"],
    },

    rs: {
      label: "Relative Strength",
      type: "select",
      options: ["Weak", "Neutral", "Strong", "Very Strong"],
      filterable: true,
      isCheck: true,
      idealValues: ["Strong"],
    },

    symmetry: {
      label: "Symmetry",
      type: "select",
      options: ["Yes", "No", "Not Applicable"],
      filterable: true,
      isCheck: false,
    },
    fractals: {
      label: "Fractals",
      type: "checkbox",
      filterable: true,
      isCheck: false,
    },

    attitude: {
      label: "Attitude",
      type: "select",
      options: ["Poor", "Average", "Good", "Excellent"],
      filterable: true,
      isCheck: true,
      idealValues: ["Good", "Excellent"],
    },

    liquidity: {
      label: "Liquidity",
      type: "select",
      options: [
        "<=20Cr",
        "21 to 49Cr",
        "50 to 99Cr",
        "100Cr to 199Cr",
        "200Cr to 499Cr",
        "500Cr+",
        "1000Cr+",
        "1500Cr+",
        "2000Cr+",
      ],
      filterable: true,
      isCheck: true,
      idealValues: [
        "100Cr to 199Cr",
        "200Cr to 499Cr",
        "500Cr+",
        "1000Cr+",
        "1500Cr+",
        "2000Cr+",
      ],
    },
    adr: {
      label: "ADR",
      type: "select",
      options: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
      filterable: true,
    },
  },

  weeks: {},
  uiConfig: {
    readOnlyPastWeeks: false,
    columnVisibility: {
      // locked columns (always true)
      __stock__: true,
      __checks__: true,
      __tradable__: true,
      // dynamic params will be injected automatically
    },
    sectors: [
      "Auto",
      "Banks",
      "Chemicals",
      "Consumer Durables / Non Durables",
      "Defence",
      "Electronics",
      "Finance",
      "IT",
      "Manufacturing",
      "Metals/Minerals",
      "Oil Refinery",
      "Pharma",
      "Miscellaneous",
      "Electricals",
      "Construction",
      "Communications",
    ],
    tags: ["IPO Base", "Large Base", "OTB", "Young IPO"],
    tagFilterable: true,
    sectorFilterable: true,
    tradableFilterable: true,
  },
};
