export const DEFAULT_DATA = {
  sectors: [
    { name: "Auto", countries: ["IN", "US"] },
    { name: "Banks", countries: ["IN", "US"] },
    { name: "Chemicals", countries: ["IN", "US"] },
    { name: "Consumer Durables / Non Durables", countries: ["IN", "US"] },
    { name: "Defence", countries: ["IN", "US"] },
    { name: "Electronics", countries: ["IN", "US"] },
    { name: "Finance", countries: ["IN", "US"] },
    { name: "IT", countries: ["IN", "US"] },
    { name: "Manufacturing", countries: ["IN", "US"] },
    { name: "Metals/Minerals", countries: ["IN", "US"] },
    { name: "Oil Refinery", countries: ["IN", "US"] },
    { name: "Pharma", countries: ["IN", "US"] },
    { name: "Miscellaneous", countries: ["IN", "US"] },
    { name: "Electricals", countries: ["IN", "US"] },
    { name: "Construction", countries: ["IN", "US"] },
    { name: "Communications", countries: ["IN", "US"] },
    { name: "Storage", countries: ["US"] },
    { name: "AI Stocks", countries: ["US"] },
    { name: "Data Center", countries: ["US"] },
  ],

  paramDefinitions: {
    stage: {
      label: "Stage",
      type: "select",
      options: ["Stage 1", "Stage 2", "Stage 3", "Stage 4"],
      filterable: true,
      isCheck: true,
      idealValues: ["Stage 2"],
    },

    rs: {
      label: "Relative Strength",
      type: "select",
      options: ["Weak", "Neutral", "Strong", "Very Strong"],
      filterable: true,
      isCheck: true,
      idealValues: ["Strong"],
    },

    symmetry: {
      label: "Symmetry",
      type: "select",
      options: ["Yes", "No", "Not Applicable"],
      filterable: true,
      isCheck: false,
    },
    fractals: {
      label: "Fractals",
      type: "checkbox",
      filterable: true,
      isCheck: false,
    },

    attitude: {
      label: "Attitude",
      type: "select",
      options: ["Poor", "Average", "Good", "Excellent"],
      filterable: true,
      isCheck: true,
      idealValues: ["Good", "Excellent"],
    },

    "in.liquidity": {
      label: "Liquidity",
      type: "select",
      options: [
        "<=20Cr",
        "21 to 49Cr",
        "50 to 99Cr",
        "100Cr to 199Cr",
        "200Cr to 499Cr",
        "500Cr+",
        "1000Cr+",
        "1500Cr+",
        "2000Cr+",
      ],
      countries: ["IN"],
      filterable: true,
      isCheck: true,
      idealValues: [
        "100Cr to 199Cr",
        "200Cr to 499Cr",
        "500Cr+",
        "1000Cr+",
        "1500Cr+",
        "2000Cr+",
      ],
    },
    "us.liquidity": {
      label: "Liquidity",
      type: "number",
      countries: ["US"],
      filterable: true,
      isCheck: false,
    },
    "in.adr": {
      label: "ADR",
      type: "select",
      options: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
      countries: ["IN"],
      filterable: true,
    },
    "us.adr": {
      label: "ADR",
      type: "number",
      countries: ["US"],
      filterable: true,
    },
  },

  watchlists: [],
  weeks: {},
  uiConfig: {
    readOnlyPastWeeks: false,
    columnVisibility: {
      // locked columns (always true)
      __stock__: true,
      __checks__: true,
      __tradable__: true,
      // dynamic params will be injected automatically
    },
    sectors: [
      { name: "Auto", countries: ["IN", "US"] },
      { name: "Banks", countries: ["IN", "US"] },
      { name: "Chemicals", countries: ["IN", "US"] },
      { name: "Consumer Durables / Non Durables", countries: ["IN", "US"] },
      { name: "Defence", countries: ["IN", "US"] },
      { name: "Electronics", countries: ["IN", "US"] },
      { name: "Finance", countries: ["IN", "US"] },
      { name: "IT", countries: ["IN", "US"] },
      { name: "Manufacturing", countries: ["IN", "US"] },
      { name: "Metals/Minerals", countries: ["IN", "US"] },
      { name: "Oil Refinery", countries: ["IN", "US"] },
      { name: "Pharma", countries: ["IN", "US"] },
      { name: "Miscellaneous", countries: ["IN", "US"] },
      { name: "Electricals", countries: ["IN", "US"] },
      { name: "Construction", countries: ["IN", "US"] },
      { name: "Communications", countries: ["IN", "US"] },
      { name: "Storage", countries: ["US"] },
      { name: "AI", countries: ["US"] },
      { name: "Data Center", countries: ["US"] },
    ],
    tags: ["IPO Base", "Large Base", "OTB", "Young IPO"],
    tagFilterable: true,
    sectorFilterable: true,
    tradableFilterable: true,
    enableApiHydration: true,
  },
};
